### ISSUE TITLE
Bug funcionalidad objetos

### ISSUE THREAD

**Issue by crannnabethadh** [miguel-jesus/ClickyCratesClient#2]
**label:bug**
No se actualizan los objetos.
No aparece nada en la tabla Objects de la base de datos.
Además lanza una excepción:
![image](https://user-images.githubusercontent.com/55758822/83755506-f6c56880-a66d-11ea-8735-806e2a16987f.png)
![image](https://user-images.githubusercontent.com/55758822/83755547-047aee00-a66e-11ea-8d75-5d45d60e4109.png)

**Comment by miguel-jesus** [comment]
Si vienes desde la Api es posible que sea el mismo error de intentar interactuar con la tabla equivocada, yo por el momento se me actualizan los objetos correctamente

**Comment by crannnabethadh** [comment]
No, la BBDD y la tabla están ok. Además se para en el breakpoint que pongo en UpdateObjects y se ejecuta la consulta a la BBDD sin generar ninguna excepción pero sigue sin aparecer nada en la tabla Objects.
En el cliente sigo recibiendo la excepcion Json de arriba.

**Comment by miguel-jesus** [comment]
Me gustaría que me detallarás todo lo que has hecho paso por paso desde la inicialización de la tabla hasta donde estas , porque a mi me sale todo ok sin problemas y si no me explicas como has hecho las cosas no podré ayudarte. y si pudieras pasar las una capturas de la data de las tablas en la API mejor

**Comment by crannnabethadh** [comment]
La tabla Objects está en blanco. No hay nada. La creé con el script que hay en la API/TableScripts/dbo.Objects.sql.
Los pasos que hago son los típicos, loguearme en el cliente, jugar partidas, volver al menu principal, logout, salir.

**Comment by miguel-jesus** [comment]
el usuario que estas usando lo registrastes por postman o en unity?

**Comment by crannnabethadh** [comment]
En Unity. Registre varios y funciona con todos. Y en la tabla ASpNetUsers y Players estan correctamente.

**Comment by miguel-jesus** [comment]
pues yo no miraría de poner un breakpoint en el get sino en la coroutine del insert de la tabla objects

**Comment by crannnabethadh** [comment]
En que línea? Qué tengo que buscar exactamente? Ya puse en el primer mensaje que saltaba una excepción JSON must represent an object type. En la linea 180.

**Comment by miguel-jesus** [comment]
Acabo de clonar tanto la Api como el cliente y no me da ningún fallo como este creando sus respectivas tablas en la Api. El método de insert está en la clase register si mal no recuerdo

**Comment by crannnabethadh** [comment]
En qué clase register? En el cliente o en la API? Hay 2 metodos insert en la clase register. Puedes especificar más los pasos que tengo que segrui para comprobar si lo estoy haciendo bien o hago algo mal?

**Comment by miguel-jesus** [comment]
Hay 3 en la clase register del cliente. Si te fijas hay 3 inserts, una coroutine hace post a AspNetUsers , otra hace post a Players , y la otra hace post a  Objects

**Comment by crannnabethadh** [comment]
Ok, he creado un nuevo usuario y ahora si que ha inicializado la tabla de Objects con su insert.
